### ISSUE TITLE
강사 관리 페이지 + 수업 관리

### ISSUE THREAD

**Issue by limdongkyu** [kimdong0/classmanagement#5]
필터 검색  이후 페이지네이터는 없는게 좋을듯 싶습니다. 혹은 전체 보기 정도만 있으면 될듯 싶습니다. 

검색 완료후 alert 창이 뜨는 이유가 있나요?

**Comment by kimdong0** [comment]
필터 검색 결과에서 페이지네이터는 숨김 처리 하겠습니다.
검색 후 Alert은 검색이 완료되었다는 알림 그 이상의 이유는 없는 것 같습니다.
Alert 노출을 생략하거나, OK버튼을 누르지 않아도 자동으로 사라지도록 수정하겠습니다.

**Comment by limdongkyu** [comment]
네~ 
Alert이 어느곳에 어떠한 이유로 사용 되는지에 대한 고민이 필요한것 같습니다.
